name: Deploy to VPS

on:
  push:
    branches: [main]
    


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/NFT1
            git pull origin main
            cd backend && npm ci --production
            pm2 restart server
            cd ../frontend/react && npm ci && npm run build
            sudo systemctl reload nginx